apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "*"
  - apiGroups:
      - storage.k8s.io
    resources:
      - pods
    verbs:
      - '*'
