apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-global
  namespace: {{ include "dcu-exporter.namespace" . }}
  labels:
    {{- include "dcu-exporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: "dcu-exporter"
subjects:
  - kind: ServiceAccount
    name: pod-reader
    namespace: {{ include "dcu-exporter.namespace" . }}
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
