{{- if .Values.serviceAccount.create -}}
# Copyright (c) 2024, Sugon CORPORATION.  All rights reserved.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: {{ include "dcu-exporter.namespace" . }}
  labels:
    {{- include "dcu-exporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: "dcu-exporter"
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
