{{- if .Values.service.enable }}
# Copyright (c) 2024, Sugon CORPORATION.  All rights reserved.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcu-exporter.fullname" . }}
  namespace: {{ include "dcu-exporter.namespace" . }}
  labels:
    {{- include "dcu-exporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: "dcu-exporter"
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "metrics"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    {{- include "dcu-exporter.selectorLabels" . | nindent 4 }}
{{- end }}
